// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shlghohvgwguzbmqmmuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNobGdob2h2Z3dndXpibXFtbXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Njc4MTAsImV4cCI6MjA3MDI0MzgxMH0.ARwy24rsBN_GTkso2tewj0pK7dz1xR5u9GcfraVBL9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});